#!/bin/bash

# Script to create .env file from .env.example

set -e

ENV_FILE=".env"
ENV_EXAMPLE=".env.example"

if [ -f "$ENV_FILE" ]; then
    echo "⚠️  .env file already exists!"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Cancelled."
        exit 0
    fi
fi

if [ ! -f "$ENV_EXAMPLE" ]; then
    echo "❌ Error: $ENV_EXAMPLE not found!"
    exit 1
fi

cp "$ENV_EXAMPLE" "$ENV_FILE"

# Generate APP_KEY if not set
if ! grep -q "APP_KEY=base64:" "$ENV_FILE"; then
    echo "🔑 Generating application key..."
    # This will be generated by Laravel later
    sed -i.bak 's/APP_KEY=$/APP_KEY=/' "$ENV_FILE"
    rm -f "${ENV_FILE}.bak"
fi

echo "✅ Created $ENV_FILE from $ENV_EXAMPLE"
echo ""
echo "📝 Next steps:"
echo "   1. Review and edit .env file if needed"
echo "   2. Run: docker-compose up -d"
echo "   3. Run: docker-compose exec app php artisan key:generate"

